<h1 style="font-size: 40px; margin-bottom: 0px;">3.1 Modeling biological phenomena (I)</h1>

<hr style="margin-left: 0px; border: 0.25px solid; border-color: #000000; width: 800px;"></hr>

This week, we gained an appreciation how quantitative approaches act as a microscope for biology, helping to reveal hidden mechanisms that our models may not have fully captured. We learned how numerical literacy can help us develop an intuition for the scales and numbers in biology, and when our expectations don't line up entirely with reality, that often means that our understanding of a phenomenon is incomplete, thereby revealing paths for further inquiry that deepen our understanding of biological phenomena. 

Like with physics and chemistry, mathematical models/simulations can be applied to the complexity and messiness of biology as well. Recall from lecture that in biology, a dialogue exists between theories and experiments, wherein theories shape the questions we ask and hypotheses we test. The resulting data and analyses then reshape and refine our theories and models, and the cycle starts again. The same dialogue exists for computational models and experiments. By taking what we know and translating it into mathematical equations, we can create computational simulations that generate predictions about some biological phenomenon. We can then take these predictions and test it against the results of real-world experiments, and discrepancies between the predictions of our computational models and empirical data indicate that our understanding is incomplete. Our computational models are then refined and further predictions can be made, and again the cycle repeats.

Today, we refresh ourselves with the fundamentals of for-loops with some independent exercises to start of this notebook reviewing operations that we've set up previously to help reinforce our understanding of for-loops. Then we'll expand a bit more on how we can add flexibility into our for-loops, and set up for-loops to build upon itself. Then we'll use for-loops to solve a simple mathematical equation (with some more plotting practice). Tomorrow, we'll take the concepts that we reviewed and learned and apply it to modeling biological phenomena.

<strong>Learning objectives:</strong>
<ul>
    <li>Practice some more basic for-loops</li>
    <li>Expanding our application of for-loops</li>
    <li>Solving mathematical equations with for-loops</li>
    <li>Some more plotting practice</li>
</ul>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

<h1 style="font-size: 40px; margin-bottom: 0px;">Exercise #1 - Review basic for-loop set up</h1>

<hr style="margin-left: 0px; border: 0.25px solid; border-color: #000000; width: 850px;"></hr>

Recall that for-loops allow you to control the flow of code and to repeatedly perform a specified operation on all the elements of a list. For this exercise, set up a list of numbers using <code>np.arange()</code> that your for-loop will iterate through, and have your for-loop print the elements of your list.

<a href="https://numpy.org/doc/2.3/reference/generated/numpy.arange.html" rel="noopener noreferrer"><u>Documentation for <code>np.arange()</code> can be found here.</u></a>

If you dig into the documentation, you'll find that <code>np.arange()</code> can be called up in a few different ways. For our use case, we'll call up the function as:

```
np.arange(start, stop, step)
```

Where <code>start</code> and <code>stop</code> specify the range <code>&lbrack;start, stop)</code>, where the start value is included and the stop value is not. The <code>step</code> parameter specifies the step size.

In [3]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [4]:
for i in np.arange(0, 10, 1):
    print(i)

0
1
2
3
4
5
6
7
8
9


You should see that the specified operation is repeated for all values of your for-loop until the end of the list (or array or other compound data type) is reached. 

<h1 style="font-size: 40px; margin-bottom: 0px;">Exercise #2 - Numerical expressions in for-loops</h1>

<hr style="margin-left: 0px; border: 0.25px solid; border-color: #000000; width: 900px;"></hr>

We can add additional complexity into our for-loops by introducing basic numerical expressions using the mathematical operators that we're familiar with. Set up a for-loop with a list/array containing values ranging from <code>&lbrack;0, 20)</code>, and have Python output the assigned values as well as the respective results from some mathematical operators:

<ul>
    <li><code>+</code></li>
    <li><code>-</code></li>
    <li><code>*</code></li>
    <li><code>/</code></li>
    <li><code>**</code></li>
    <li><code>//</code> - floor division operator that returns the quotient (rounded down)</li>
    <li><code>%</code> - modulus operator that returns the value of the remainder following division by the right-side value</li>
</ul>

In [7]:
for i in np.arange(0, 20, 1):
    print(i % 3)


0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1
2
0
1


<h1 style="font-size: 40px; margin-bottom: 0px;">Exercise #3 - Iterate through two lists simultaneously</h1>

<hr style="margin-left: 0px; border: 0.25px solid; border-color: #000000; width: 950px;"></hr>

Recall that we can also set up for-loops to iterate through two lists simultaneously. This can be helpful when we need specific values to be paired up with one another, so their positions in their respective lists are important to maintain.

To do this, we can make use of the <code>zip()</code> function. <a href="https://docs.python.org/3.13/library/functions.html#zip" rel="noopener noreferrer"><u>Documentation for <code>zip()</code> can be found here.</u></a>

If we dig into the documentation, we can see that we specify multiple iterable objects, such as lists and arrays, and their values will be combined when they are iterated on through a for-loop.

For this exercise, set up two lists of equal length and assign them to their own variable. The lists can be in a range that you define using <code>np.arange()</code>. Then select a math operator to use with values pulled from these two lists in a for-loop. Have the for-loop print out the results of your numerical expression.

In [9]:
len(np.arange(0, 21, 1))

21

In [12]:
victor = np.arange(0, 21, 1)
liebchen = np.arange(0, 42, 2)

In [13]:
for i, j in zip(victor, liebchen):
    print(i * j)

0
2
8
18
32
50
72
98
128
162
200
242
288
338
392
450
512
578
648
722
800


You don't necessarily need to be limited to two compound data types. You can also use the same set up to iterate through three or more lists/arrays simultaneously. Give that a try below using three lists.

In [14]:
ludwig = np.arange(100, 121, 1)

In [15]:
len(ludwig)

21

In [16]:
for a, b, c in zip(victor, liebchen, ludwig):
    print(a + b + c)

100
104
108
112
116
120
124
128
132
136
140
144
148
152
156
160
164
168
172
176
180


<h1 style="font-size: 40px; margin-bottom: 0px;">Exercise #4 - Nested for-loops</h1>

<hr style="margin-left: 0px; border: 0.25px solid; border-color: #000000; width: 650px;"></hr>

In the above examples, the list contained noncomposite data types. However, the iterable object doesn't necessarily need to be comprised of just noncomposite data types. If your iterable object contains lists within a list, then your for loop will perform its specified operation on each list. This allows you to also set up a for loop to iterate through those lists if your specified operation is a for-loop.

For this exercise, pull together your lists that you created in exercise #3 into a single list. Then set up a standard for-loop to output each list.

In [17]:
cat = [victor, liebchen, ludwig]

In [18]:
cat

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20]),
 array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
        34, 36, 38, 40]),
 array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119, 120])]

Then modify your code to set up a nested for-loop that will iterate through each element of each list and print out the value.

In [20]:
for i in cat:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120


<h1 style="font-size: 40px; margin-bottom: 0px;">Exercise #5 - Conditional operations in for-loops</h1>

<hr style="margin-left: 0px; border: 0.25px solid; border-color: #000000; width: 900px;"></hr>

We can also combine for-loops with conditional statements to further control how our for-loop runs. For example, set up a list/array with values ranging from <code>&lbrack;0, 20)</code> with a step size of 1. Then set up a for-loop whose output is dictated by whether or not an element in your list/array is divisible by 3.

If the element in your list is divisible by 3, have Python output the string <code>'Victor'</code>, and when it is not divisible by 3, have Python output <code>'Liebchen'</code> instead.

In [21]:
for i in np.arange(0, 20, 1):
    if (i % 3) == 0:
        print(i, 'victor')
    else:
        print(i, 'liebchen')
        

0 victor
1 liebchen
2 liebchen
3 victor
4 liebchen
5 liebchen
6 victor
7 liebchen
8 liebchen
9 victor
10 liebchen
11 liebchen
12 victor
13 liebchen
14 liebchen
15 victor
16 liebchen
17 liebchen
18 victor
19 liebchen


You should see that while the for-loop continues to iterate through all elements of the given list, the output/operation can change depending on the condition specified, allowing you to control what type of operation is performed as Python works its way through your iterable object.

<h1 style="font-size: 40px; margin-bottom: 0px;">Exercise #6 - Generating usable outputs</h1>

<hr style="margin-left: 0px; border: 0.25px solid; border-color: #000000; width: 900px;"></hr>

Recall that we can also generate usable outputs from our for-loops by initializing some mutable compound data type that can accept/hold onto the outputs generated by our for-loop. We can do this in a number of different ways, but one common way is to initialize an empty list. 

For the first part of this exercise, initialize an empty list and assign it to a variable. Then set up a for-loop that iterates through one of the iterable objects you created in exercise #3, and perform some mathematical operation on each element. Then to create a usable output, use the <code>list.append()</code> function to add the output to your initialized list.

In [ ]:
barbara = []

for i in victor:
    barbara.append(i**2)
    print(barbara)

You should see that there's no output printed out when the for-loop runs. This is because we're appending the outputs to our initialized list. Let's quickly take a look at the contents of our list to see how it has been updated.

In [24]:
print(barbara)

[np.int64(0), np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25), np.int64(36), np.int64(49), np.int64(64), np.int64(81), np.int64(100), np.int64(121), np.int64(144), np.int64(169), np.int64(196), np.int64(225), np.int64(256), np.int64(289), np.int64(324), np.int64(361), np.int64(400)]


Another common data type used to hold outputs is an array. However, recall that unlike lists, arrays must be created with a defined size, and a straightforward way to do so is to use the <code>np.zeros()</code> function. This function initializes an array of zeros according to the shape that you provide the function. <a href="https://numpy.org/doc/stable/reference/generated/numpy.zeros.html" rel="noopener noreferrer"><u>Documentation for <code>np.zeros()</code> can be found here.</u></a>.

Digging into the documentation, you can see that we can provide an integer to create a one-dimensional array of zeros or a tuple to create a multi-dimensional array of zeros.

For this part of exercise #6, initialize a one-dimensional array of zeros of size 20.

In [26]:
tony = np.zeros(20)

print(tony)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Now set up a for-loop using <code>np.arange()</code> that spans <code>[0, 20)</code> with a step size of 1, and perform a specified mathematical operation on each element of this array. Then assign the result of that operation to your array of zeros.

In [33]:
tony = np.zeros(20)

for i in np.arange(0, 20, 1):
    tony[i] = i + 2

print(tony)

[ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18. 19.
 20. 21.]


What you can see is that with this set up, we can have our array of zeros hold onto our outputs by assigning them to a spot in the array of zeros based on index position. 

<h2>Use the output in subsequent operations</h2>

By assigning our outputs to an array, we can then perform additional operations on our outputs. For example, see if you can add 10 to each element of your now updated array.

In [34]:
tony **2

array([  4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100., 121., 144.,
       169., 196., 225., 256., 289., 324., 361., 400., 441.])

You can also use the array to calculate descriptive statistics of the outputs as well. Give that a try below.

In [35]:
np.mean(tony)

np.float64(11.5)

<h1 style="font-size: 40px; margin-bottom: 0px;">Exercise #7 - Pulling in elements based on position</h1>

<hr style="margin-left: 0px; border: 0.25px solid; border-color: #000000; width: 900px;"></hr>

You might notice that a potential issue that can arise when we assign values to an initialized array of zeros is that if the list that we're interested in iterating through can't double as an index position. For example, what if we wanted to iterate through a list whose range can be defined by the range <code>&lbrack;100, 140)</code> with a step size of 2?

See if you can set up a for-loop that can pull in elements of a list defined by the range <code>&lbrack;100, 140)</code> with a step size of 2, then perform some specified mathematical operation, and then assign the results to an array of zeros of length 20.

In [40]:
tony = np.zeros(20)
print(tony)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [43]:
tony = np.zeros(20)

for i in np.arange(100, 140, 2):
    tony[i] = i * 2

IndexError: index 100 is out of bounds for axis 0 with size 20

In [42]:
tony

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.,
       26., 28., 30., 32., 34., 36., 38.])

In [44]:
tony = np.zeros(20)
values = np.arange(100, 140, 2)
position_index = np.arange(0, 20, 1)

for i in position_index:
    tony[i] = values[i] * 2

In [45]:
tony

array([200., 204., 208., 212., 216., 220., 224., 228., 232., 236., 240.,
       244., 248., 252., 256., 260., 264., 268., 272., 276.])

<h1 style="font-size: 40px; margin-bottom: 0px;">Setting up more flexible for-loops</h1>

<hr style="margin-left: 0px; border: 0.25px solid; border-color: #000000; width: 700px;"></hr>

What you may have noticed from exercise #7 is that we manually defined our iterable object and the size of our array of zeros. We can add in a little bit more flexibility by making use of the built-in <code>len()</code> function, which outputs the length of a compound data type, such as a list or array. <a href="https://docs.python.org/3/library/functions.html#len" rel="noopener noreferrer"><u>Documentation for <code>len()</code> can be found here.</u></a>

What this then allows us to do is to specify the length of our array of zeros and our array used to initialize our for-loop and have it adapt to the length of some other compound data type that we want to pull in.

In [50]:
import pandas as pd

In [ ]:
barbara = np.arange(1000, 1100, 3)

tony = np.zeros(len(barbara))

for i in np.arange(0, len(barbara), 1):
    tony[i] = barbara[i] % 5

new_tony = pd.DataFrame({'hi': tony})
new_tony.style

And we can play around with the length of our list, and our array of zeros and for-loop will adapt to it.

<h1 style="font-size: 40px; margin-bottom: 0px;">Build upon previous values</h1>

<hr style="margin-left: 0px; border: 0.25px solid; border-color: #000000; width: 700px;"></hr>

By taking advantage of the position information of your arrays, you can set up for loops that take into account the previous output when generating each subsequent outputs. However, you will want to keep in mind how you are setting up your index to avoid pulling from an index position that is out of bounds for your array.

<h2>Small exercise</h2>

See if you can below, write out a for loop where you start with an array of zeros, and initialize a for-loop that is adaptable to the length of our array. Within the for-loop set up an operation where you add 20 to the previous value each time the for-loop iterates through a position array. 

In [75]:
print(apple[29])

58.0


In [73]:
position_index = np.arange(0, len(apple)-1, 1)

In [74]:
print(position_index[-1])

28


In [76]:
apple = np.zeros(30)

for i in np.arange(1, len(apple), 1):
    apple[i] = apple[i-1] + 2

In [63]:
apple

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.,
       26., 28., 30., 32., 34., 36., 38., 40., 42., 44., 46., 48., 50.,
       52., 54., 56., 58.])

Then let's adjust the size of your array of zeros and see how the for-loop adapts. You should see that your for-loop should be able to adapt to the changing size of your initialized array of zeros.

<h1 style="font-size: 40px; margin-bottom: 0px;">Provide an initial parameter</h1>

<hr style="margin-left: 0px; border: 0.25px solid; border-color: #000000; width: 600px;"></hr>

One thing to note is that with the previous setup, your first value will by default be zero, but we can take what we know about compound data types to set up an initial parameter that will assign a value to the first element of our array. After you initialize your array of zeros to store your outputs, you can manually set the first element in the array to a desired initial value. 

Now that we set an initial value, let's take what we've learned about building on previous values and setting an initial value to run a for-loop where our starting value is  1 and we add 20 to the previous value each iteration of our for-loop.

<h1 style="font-size: 40px; margin-bottom: 0px;">Exercise #8 - Fibonacci sequence using for-loops</h1>

<hr style="margin-left: 0px; border: 0.25px solid; border-color: #000000; width: 900px;"></hr>

For this exercise, see if you can take what you've learned so far to create a Fibonacci sequence. Your final output can have 25 values.

Generate a line plot of your Fibonacci sequence

<h1 style="font-size: 40px; margin-bottom: 0px;">Exercise #9 - Solve the equation for a line</h1>

<hr style="margin-left: 0px; border: 0.25px solid; border-color: #000000; width: 800px;"></hr>

Because for-loops repeatedly perform a set operation through a defined index, we can use it to solve mathematical equations (over a defined interval). 

For this exercise, recall the equation for a line, and use what you've learned in this notebook to translate it into an expression that Python would understand. Then initialize a for-loop to solve the equation from x=0 to x=30.

Let's plot our results real quick to see how they look.

<h1 style="font-size: 40px; margin-bottom: 0px;">Exercise #10 - Solve a polynomial</h1>

<hr style="margin-left: 0px; border: 0.25px solid; border-color: #000000; width: 700px;"></hr>

For this exercise, try to see if you can again take what you've learned to have Python solve a polynomial equation and plot the resulting output.

Recall the general equation for a polynomial:

```
y = Ax**n + Bx**n-1 + ... + Z
```

Feel free to make it as simple or as complicated of a polynomial as you want to see how Python handles it. Then plot the output.

<h1 style="font-size: 40px; margin-bottom: 0px;">Exercise #11 - Solve for negative values of x</h1>

<hr style="margin-left: 0px; border: 0.25px solid; border-color: #000000; width: 800px;"></hr>

What you've probably noticed is that so far, we've been solving only for positive values of x in our equations, but as we know, x can also be negative for mathematical expressions. To wrap up, see if you can take what you've learned in this notebook to get Python to solve your polynomial for <u>both positive and negative values of x</u>.

Then plot the output.

<h2>Small guided section: Adjusting axis spines</h2>

You'll likely see that the spines of the axes are still along the border of the plot. To adjust the position of the spines, you can set up your figure using the usual method:

```
fig, ax = plt.subplots()

plt.plot(your_x_values, your_y_values)
```

Then you can pull out the <code>spines</code> container from our <code>ax</code> object, allowing us to adjust the axis spines positioning to be more intuitive for us (centered on the origin). 

```
ax.spines[['left', 'bottom']].set_position('zero')
```

The above is pulling the left and bottom spines and setting their position to be at (0,0). In other words, the horizontal axis will be at y=0 and the vertical axis will be at x=0.

Lastly, we can use <code>seaborn</code> to remove the top and right spines.

```
sns.despine()
```